version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - libdjvulibre-dev
  jobs:
    pre_build:
      - python setup.py build_ext --inplace
      - export PYTHONPATH=$PWD

sphinx:
  configuration: doc/api/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
