version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  apt_packages:
    - libdjvulibre-dev
    - graphviz

sphinx:
  configuration: doc/api/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
