language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
before_install:
 - sudo apt-get update
 - sudo apt-get install -y libdjvulibre-dev djvulibre-bin
install:
 - pip install cython
script:
 - python setup.py build_ext --inplace
 - nosetests --verbose
