language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
before_install:
- sudo apt-get update
- sudo apt-get install -y libdjvulibre-dev djvulibre-bin
install:
- pip install cython
- pip install sphinx
script:
- python setup.py build_ext --inplace
- nosetests --verbose
- PYTHONPATH=$PWD sphinx-build -b doctest doc/source/ tmp

# vim:ts=2 sts=2 sw=2 et
