language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
before_install:
- sudo apt-get update
- sudo apt-get install -y libdjvulibre-dev djvulibre-bin
install:
- pip install cython
- '[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install sphinx'
script:
- python setup.py build_ext --inplace
- nosetests --verbose
- '[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || PYTHONPATH=$PWD sphinx-build -b doctest doc/source/ tmp'

# vim:ts=2 sts=2 sw=2 et
