language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- nightly
env:
- DJVULIBRE_VERSION=3.5.23
- DJVULIBRE_VERSION=3.5.27
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
install:
- export PATH="/usr/lib/ccache:$PATH"
- wget http://downloads.sourceforge.net/djvu/djvulibre-${DJVULIBRE_VERSION}.tar.gz
- tar -xvvf djvulibre-*.tar.gz
- (cd djvulibre-*/ && ./configure --prefix="$HOME/opt/djvulibre" CXXFLAGS="-fpermissive -include cstddef")
- make -C djvulibre-*/libdjvu/ install
- make -C djvulibre-*/tools/ install
- export PATH="$HOME/opt/djvulibre/bin/:$PATH"
- export CPATH="$HOME/opt/djvulibre/include/"
- export PKG_CONFIG_PATH="$HOME/opt/djvulibre/lib/pkgconfig/"
- export LD_LIBRARY_PATH="$HOME/opt/djvulibre/lib/"
- pip install --upgrade pip
- pip install --build build-cython cython
- '[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install sphinx'
script:
- python setup.py build_ext --inplace
- nosetests --verbose
- '[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || PYTHONPATH=$PWD sphinx-build -b doctest doc/api/ tmp'
- python setup.py sdist
- '! tar -tvf dist/*.tar.gz | grep -F /djvu/config.pxi'

# vim:ts=2 sts=2 sw=2 et
