dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
env:
- DJVULIBRE_VERSION=3.5.27 CYTHON_VERSION=
matrix:
  include:
  - python: "2.6"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.19
  - python: "2.7"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.19
  - python: "3.2"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.20
  - python: "3.3"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.20
  - python: "3.4"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.20
  - python: "3.5"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.20
  # Python 3.6+ doesn't work with ancient Cython versions:
  # https://bugs.python.org/issue26519
branches:
  except:
  - appveyor
addons:
  apt:
    packages:
    - language-pack-ja
    - ghostscript
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
install:
- export PATH="/usr/lib/ccache:$PATH"
- wget https://downloads.sourceforge.net/project/djvu/DjVuLibre/${DJVULIBRE_VERSION}/djvulibre-${DJVULIBRE_VERSION}.tar.gz
- tar -xvvf djvulibre-*.tar.gz
- (cd djvulibre-*/ && ./configure --prefix="$HOME/opt/djvulibre" CXXFLAGS="-fpermissive -include cstddef")
- make -C djvulibre-*/libdjvu/ install
- make -C djvulibre-*/tools/ install
- \[ "$DJVULIBRE_VERSION" = "3.5.21" ] || make -C djvulibre-*/ install
- export PATH="$HOME/opt/djvulibre/bin/:$PATH"
- export CPATH="$HOME/opt/djvulibre/include/"
- export PKG_CONFIG_PATH="$HOME/opt/djvulibre/lib/pkgconfig/"
- export LD_LIBRARY_PATH="$HOME/opt/djvulibre/lib/"
- if [ "$TRAVIS_PYTHON_VERSION" = 3.2 ] && [ -z "$CYTHON_VERSION" ]; then CYTHON_VERSION=0.26.1; fi
- pip install --build build-cython cython${CYTHON_VERSION:+==$CYTHON_VERSION}
- \[ "$TRAVIS_PYTHON_VERSION" = "2.6" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.3" ] || use_sphinx=yes
- \[ -z "$use_sphinx" ] || pip install sphinx
before_script:
- python setup.py build_ext --inplace
script:
- LC_ALL=C nosetests --verbose
- \[ -z "$use_sphinx" ] || PYTHONPATH=$PWD sphinx-build -b doctest doc/api/ tmp
- \[ -z "$use_sphinx" ] || private/check-rst
- python setup.py sdist
- tar -tvf dist/*.tar.gz | { ! grep -F /djvu/config.pxi; }
- python setup.py install
- cd /
- python -c 'import djvu.sexpr, djvu.decode'

# vim:ts=2 sts=2 sw=2 et
